//get indexPath by clicking or somet other gesture. gesture generated by cntrl+drag

    @IBAction func <gesture:sender> {
        let loc: CGPoint = sender.locationInView(self.tableView)
        let indexPath: NSIndexPath = self.tableView.indexPathForRowAtPoint(loc)!
            print(tableData[indexPath.row])
    }



    func tableView(tableView: UITableView, canEditRowAtIndexPath indexPath: NSIndexPath) -> Bool {
        return true
    }
    
    func tableView(tableView: UITableView, commitEditingStyle editingStyle: UITableViewCellEditingStyle, forRowAtIndexPath indexPath: NSIndexPath) {
        if editingStyle == .Delete {
        let itemToDelete = tableItems[indexPath.row]
        managedObjectContext?.deleteObject(itemToDelete)
        tableView.deleteRowsAtIndexPaths([indexPath], withRowAnimation: .Automatic)
        }
        
    }

