//get indexPath by clicking or somet other gesture. gesture generated by cntrl+drag

    @IBAction func <gesture:sender> {
        let loc: CGPoint = sender.locationInView(self.tableView)
        let indexPath: NSIndexPath = self.tableView.indexPathForRowAtPoint(loc)!
            print(tableData[indexPath.row])
    }



    func tableView(tableView: UITableView, canEditRowAtIndexPath indexPath: NSIndexPath) -> Bool {
        return true
    }
    
    func tableView(tableView: UITableView, commitEditingStyle editingStyle: UITableViewCellEditingStyle, forRowAtIndexPath indexPath: NSIndexPath) {
        if editingStyle == .Delete {
        let itemToDelete = tableItems[indexPath.row]
        managedObjectContext?.deleteObject(itemToDelete)
        tableView.deleteRowsAtIndexPaths([indexPath], withRowAnimation: .Automatic)
        }
        
    }


//table view on custom uiview
//must implement protocols (at least):
 UITableViewDataSource, UITableViewDelegate

//and functions:
    func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    }
    
    func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCellWithIdentifier("cell1", forIndexPath: indexPath) as UITableViewCell
        return cell
        
    }
// after that you must wire tableview (cntr+drag @ storryboard) to your view controller
