//get indexPath by clicking or somet other gesture. gesture generated by cntrl+drag

    @IBAction func <gesture:sender> {
        let loc: CGPoint = sender.locationInView(self.tableView)
        let indexPath: NSIndexPath = self.tableView.indexPathForRowAtPoint(loc)!
            print(tableData[indexPath.row])
    }


